- Changelog.md
- bitbucket-pipelines.yml
- src/CMakeLists.txt
- src/Filesystem_TEST.cc
Signed-off-by: Louise Poubel <louise@openrobotics.org>
> [ign-common1] Update BitBucket links

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [master] Workflow updates

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [ign-common3] Workflow updates

- .github/CODEOWNERS
- .github/ci-bionic/after_make.sh
- .github/workflows/ci-bionic.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
- README.md
- codecov.yml
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update badges
* Add `CODEOWNERS`
* This needs https://github.com/ignition-tooling/ubuntu-bionic-ci-action/pull/4 for the examples compilation to work.
> [ign-common1] Workflow updates

- events/BUILD.bazel
- graphics/BUILD.bazel
- graphics/src/Animation_TEST.cc
- graphics/src/ColladaExporter_TEST.cc
- graphics/src/ColladaLoader_TEST.cc
- graphics/src/Dem_TEST.cc
- graphics/src/GTSMeshUtils_TEST.cc
- graphics/src/ImageHeightmap_TEST.cc
- graphics/src/Image_TEST.cc
- graphics/src/Material_TEST.cc
- graphics/src/MeshManager_TEST.cc
- graphics/src/Mesh_TEST.cc
- graphics/src/OBJLoader_TEST.cc
- graphics/src/SVGLoader_TEST.cc
- graphics/src/SubMesh_TEST.cc
- graphics/src/tinyxml2/BUILD.bazel
- profiler/BUILD.bazel
- profiler/src/Remotery/BUILD.bazel
All the tests in graphics are failing due to `IGN_HOMEDIR` needing to be set.
The remotery test for the profiler is failing due to `IGN_PROFILER_ENABLE` and `IGN_PROFILER_VALID` needing to be true.  We could manually set these, but I wasn't sure how exactly we want to go about this.
Signed-off-by: John Shepherd <john@openrobotics.org>
> [Bazel] Add graphics, profiler, tests

- .github/ci-bionic/packages.apt
- BUILD.bazel
- CMakeLists.txt
- av/BUILD.bazel
- events/BUILD.bazel
- graphics/BUILD.bazel
- graphics/src/ImageHeightmap_TEST.cc
- graphics/src/Image_TEST.cc
- profiler/BUILD.bazel
- src/Console_TEST.cc
- src/Filesystem_TEST.cc
- src/PluginLoader_TEST.cc
- test/BUILD.bazel
- test/test_util.hh
> [Bazel] Fix all of the ign_common tests under bazel

- BUILD.bazel
- av/BUILD.bazel
- events/BUILD.bazel
- graphics/BUILD.bazel
- profiler/BUILD.bazel
> Utilize new export macro

- graphics/include/ignition/common/Animation.hh
- graphics/src/Animation.cc
> Cleanup: Drop unused forward declaration

- graphics/src/ColladaExporter_TEST.cc
> Fix ColladaExport test and add pathJoins

- src/Util.cc
Otherwise we might get ODR issue with `ign-msgs/src/Utility.cc`.
> Make ignstrtok private to Util.cc

- CMakeLists.txt
- Changelog.md
https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.10.0...ign-common3
> Prepare for 3.10.1

- graphics/include/ignition/common/MeshManager.hh
- graphics/src/MeshManager.cc
- graphics/src/SubMesh_TEST.cc
Related with this issue https://github.com/ignitionrobotics/ign-common/issues/140
> Added ellipsoid mesh

- BUILD.bazel
- av/BUILD.bazel
- av/src/VideoEncoder.cc
- events/BUILD.bazel
- graphics/BUILD.bazel
- graphics/src/ColladaExporter.cc
- graphics/src/SVGLoader.cc
- profiler/BUILD.bazel
- src/Filesystem_TEST.cc
- src/PluginLoader_TEST.cc
- test/BUILD.bazel
This introduces necessary infrastructure and changes to make ign-common build with Bazel.
> Add bazel buildsystem support

- CMakeLists.txt
- Changelog.md
Preparation for 4.0.0 release.
No previous release!
> Prepare for 4.0.0~pre1

- CMakeLists.txt
- Changelog.md
Preparation for 4.0.0~pre2 release.
Comparison to 4.0.0~pre1: https://github.com/ignitionrobotics/ign-common/compare/ignition-common4_4.0.0-pre1...main
> 🎈 4.0.0~pre2

- examples/README.md
Improved examples/README.md instrucctions to compile examples on Windows
> Include windows instructions in examples README.md

- CMakeLists.txt
- Changelog.md
Preparation for 3.13.1 release.
Comparison to 3.13.0: https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.13.0...ign-common3
Fixes Fuel download.
> 3 13 1 prep

- BUILD.bazel
- CMakeLists.txt
- Changelog.md
Preparation for 3.13.2 release.
Comparison to 3.13.1: https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.13.1...ign-common3
Needed by https://github.com/ignitionrobotics/ign-fuel-tools/pull/178
> Prepare for 3.13.2 release

- CMakeLists.txt
- Changelog.md
Preparation for 4.3.0~pre1 pre-release.
Comparison to <4.2.0>: https://github.com/ignitionrobotics/ign-common/compare/ignition-common4_4.2.0...ign-common4
> 🎈 4.3.0~pre1

- tutorials/install.md
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>
Add macos install instructions
> Add macos install instructions

- Changelog.md
- examples/CMakeLists.txt
- examples/logging_performance.cc
- src/Filesystem.cc
- src/URI.cc
Port ign-common4 to main
This will conflict with #238 
Branch comparison: https://github.com/ignitionrobotics/ign-common/compare/main...ign-common4
> Merge 4 -> main

- src/Filesystem_TEST.cc
Test changes for #238, broken out for easier review.
> Update tests to use more STL functionality

- .github/ci/packages.apt
This should help with #320
This isn't needed anymore and has issues on Jammy.
> packages.apt: don't install ruby-ronn

- src/URI.cc
> Fix spelling

- src/Console.cc
- test/integration/console.cc
Port ign-common3 to ign-common4
Branch comparison: https://github.com/ignitionrobotics/ign-common/compare/ign-common4...ign-common3?expand=1
> 3 to 4 20220331

- src/Console.cc
- src/URI.cc
- test/integration/console.cc
Port ign-common4 to main
Branch comparison: https://github.com/ignitionrobotics/ign-common/compare/main...ign-common4
> 4 to 5 20220401

- examples/CMakeLists.txt
Related to https://github.com/ignition-tooling/release-tools/pull/700
Use ignition-common5_VERSION_MAJOR to aid search/replace scripts.
> examples/CMakeLists.txt: fix find version variable

- .github/ci/packages.apt
- CMakeLists.txt
See https://github.com/ignition-tooling/release-tools/issues/685
> Bumps in garden : ign-common5

- CMakeLists.txt
- av/include/gz/common/CMakeLists.txt
- av/src/CMakeLists.txt
- events/include/gz/common/CMakeLists.txt
- events/src/CMakeLists.txt
- geospatial/include/gz/common/CMakeLists.txt
- geospatial/src/CMakeLists.txt
- graphics/include/gz/common/CMakeLists.txt
- graphics/src/CMakeLists.txt
- include/gz/common/CMakeLists.txt
- profiler/src/CMakeLists.txt
- src/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/performance/CMakeLists.txt
- test/regression/CMakeLists.txt
- testing/include/gz/common/CMakeLists.txt
- testing/src/CMakeLists.txt
* Part of https://github.com/gazebo-tooling/release-tools/issues/719
> [ign -> gz] CMake functions

- include/ignition/common/Console.hh
- src/Console.cc
- src/Util.cc
- test/performance/logging.cc
> Backport: Synchronize console (#227) and FileLogger (#378) writes

- BUILD.bazel
- CMakeLists.txt
- av/BUILD.bazel
- av/src/CMakeLists.txt
- events/BUILD.bazel
- events/src/CMakeLists.txt
- examples/CMakeLists.txt
- geospatial/src/CMakeLists.txt
- graphics/BUILD.bazel
- graphics/src/CMakeLists.txt
- profiler/BUILD.bazel
- profiler/src/CMakeLists.txt
- src/CMakeLists.txt
- test/BUILD.bazel
- test/integration/CMakeLists.txt
* See https://github.com/ignition-tooling/release-tools/issues/718
* Needs
* https://github.com/gazebosim/gz-utils/pull/57
* https://github.com/gazebosim/gz-math/pull/420
> Rename CMake project to gz

- Changelog.md
- Migration.md
- README.md
- api.md.in
- configure.bat
- examples/README.md
- include/gz/common/SuppressWarning.hh
- profiler/src/CMakeLists.txt
- profiler/src/RemoteryProfilerImpl.cc
- src/PluginUtils_TEST.cc
- src/SignalHandler.cc
- src/SignalHandler_TEST.cc
- src/URI.cc
- test/performance/CMakeLists.txt
- testing/include/gz/common/testing/TestPaths.hh
- tutorials.md.in
- tutorials/hw-encoding.md
- tutorials/install.md
- tutorials/profiler.md
See: https://github.com/gazebo-tooling/release-tools/issues/757
> ign -> gz Partial Docs Migration and Project Name Followups : gz-common

- Changelog.md
- README.md
- src/SystemPaths.cc
- src/SystemPaths_TEST.cc
- test/performance/logging.cc
- tutorials/profiler.md
Port `ign-common4 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-common/compare/main...ign-common4
> Merge ign-common4 ➡️  main

- src/Console_TEST.cc
- src/Filesystem_TEST.cc
- src/PluginLoader_TEST.cc
- src/SystemPaths_TEST.cc
- testing/include/gz/common/testing/TestPaths.hh
- testing/include/gz/common/testing/detail/AutoLogFixture.hh
- testing/src/TestPaths.cc
See: https://github.com/gazebo-tooling/release-tools/issues/767
> ign -> gz Provisional Finale: Source Migration : gz-common

- CMakeLists.txt
- api.md.in
- coverage.ignore.in
- tutorials.md.in
Port `ign-common3 ` ➡️  `ign-common4`
Branch comparision: https://github.com/ignitionrobotics/ign-common/compare/ign-common4...ign-common3
> Merge ign-common3 ➡️  ign-common4

- .github/workflows/macos.yml
- BUILD.bazel
- CMakeLists.txt
- Changelog.md
- av/BUILD.bazel
- events/BUILD.bazel
- examples/CMakeLists.txt
- graphics/BUILD.bazel
- profiler/BUILD.bazel
- tutorials/profiler.md
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
> ⬆️  Bump main to 6.0.0~pre1

- av/src/AudioDecoder.cc
Port `gz-common5 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-common/compare/main...gz-common5
> Merge gz-common5 ➡️  main

- tutorials/install.md
Updated install instructions gz-common5. Related to https://github.com/gazebosim/garden-tutorial-party/issues/51
> Updated install instructions gz-common5

- tutorials/hw-encoding.md
Related to https://github.com/gazebosim/garden-tutorial-party/issues/43
> Improved visualization hw encoding tutorial gz-common5

- Changelog.md
Preparation for 5.0.0 release.
Comparison to <4.5.2>: https://github.com/gazebosim/gz-common/compare/ignition-common4_4.5.2...gz-common5
Needed by <PR(s)>
> Update changelogs for common 5.0.0

- graphics/include/gz/common/MeshManager.hh
- graphics/src/MeshManager.cc
Related with https://github.com/gazebosim/gz-sim/issues/1725
> Fixed MeshManager Singleton

- CMakeLists.txt
- Changelog.md
Preparation for 4.6.0 release.
Comparison to 4.5.2: https://github.com/gazebosim/gz-common/compare/ignition-common4_4.5.2...ign-common4
> 🎈 4.6.0 release

- CMakeLists.txt
- io/BUILD.bazel
- io/include/CMakeLists.txt
- io/include/gz/CMakeLists.txt
- io/include/gz/common/CMakeLists.txt
- io/include/gz/common/CSVStreams.hh
- io/include/gz/common/DataFrame.hh
- io/include/gz/common/Io.hh
- io/src/CMakeLists.txt
- io/src/CSVStreams.cc
- io/src/CSVStreams_TEST.cc
- io/src/DataFrame_TEST.cc
- src/CMakeLists.txt
Cherry-picked https://github.com/gazebosim/gz-common/pull/402, https://github.com/gazebosim/gz-common/pull/435, and https://github.com/gazebosim/gz-common/pull/446.
> [Backport] CSV data support

- CMakeLists.txt
- Changelog.md
Preparation for 5.2.0 release.
Comparison to 5.1.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.1.0...gz-common5
Needed by https://github.com/gazebosim/gz-sim/pull/1616
> 5.2.0 release

- Changelog.md
- graphics/include/gz/common/SubMesh.hh
- graphics/src/AssimpLoader.cc
- graphics/src/Mesh_TEST.cc
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
- io/include/gz/common/DataFrame.hh
- io/src/CSVStreams.cc
- io/src/CSVStreams_TEST.cc
- io/src/DataFrame_TEST.cc
Port gz-common5 to main
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common5
> port: 5 to main 2022-11-16

- av/src/VideoEncoder.cc
- geospatial/src/Dem.cc
- graphics/include/gz/common/Image.hh
- graphics/src/Image.cc
- graphics/src/Image_TEST.cc
- graphics/src/Mesh_TEST.cc
- graphics/src/SubMesh_TEST.cc
- test/integration/mesh.cc
> bug: Fix issues detected by ASAN

- CMakeLists.txt
- Changelog.md
Preparation for 4.6.2 release.
Comparison to 4.6.1: https://github.com/gazebosim/gz-common/compare/ignition-common4_4.6.1...ign-common4
> 4.6.2 release

- CMakeLists.txt
- Changelog.md
Preparation for 5.3.1 release.
Comparison to 5.3.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.3.0...gz-common5
Needed by <PR(s)>
> 5.3.1 release

- Changelog.md
> Update version in Changelog

- tutorials/profiler.md
This tutorial was rendering improperly, see [here](https://gazebosim.org/api/common/5/profiler.html).
> Fix profile tutorial

- .github/CODEOWNERS
> Add marcoag as codeowner

- graphics/include/gz/common/MeshManager.hh
- graphics/src/MeshManager.cc
See #451
**Note to maintainers**: Remember to use **Rebase-and-merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.
> Cherry-pick #451: Fixed MeshManager Singleton 

- graphics/include/gz/common/Image.hh
Backport of #437 to ign-common3.
> [Backport] Include cstring for memcpy

- profiler/src/RemoteryProfilerImpl.hh
add stdlint.h to fix compiling failure
69/86] Building CXX object profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o FAILED: profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o  /usr/bin/c++ -DGZ_PROFILER_ENABLE=1 -DGZ_PROFILER_REMOTERY=1 -DRMT_USE_METAL=0 -Dgz_common5_profiler_EXPORTS -I/home/r/software/gazebosim/gz-common/include -I/home/r/build/gz-common5/include -I/home/r/software/gazebosim/gz-common/profiler/include -I/home/r/build/gz-common5/profiler/include -I/home/r/software/gazebosim/gz-common/profiler/src/Remotery/lib -I/home/r/build/gz-common5/profiler/src -I/home/r/build/gz-common5/core/include -isystem /usr/local/include/gz/utils2 -isystem /usr/include/uuid -O2 -g -DNDEBUG  -Wall -Wextra -Wno-long-long -Wno-unused-value …
> Fix compiling under linux

- .github/workflows/macos.yml
- .github/workflows/triage.yml
- CMakeLists.txt
- Changelog.md
- README.md
- examples/CMakeLists.txt
- graphics/src/AssimpLoader.cc
- test/integration/CMakeLists.txt
- tutorials/profiler.md
Port gz-common5 to main
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common5
> Merge: 5 -> main

- graphics/src/AssimpLoader.cc
> Replace ignerr with gzerr 

- CMakeLists.txt
- Changelog.md
Preparation for 5.5.1 release.
Comparison to 5.5.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.5.0...gz-common5
> Prepare for 5.5.1 Release

- av/src/AudioDecoder.cc
- av/src/Video.cc
Port `ign-common4 ` ➡️  `gz-common5`
Branch comparison: https://github.com/gazebosim/gz-common/compare/gz-common5...ign-common4
> Merge ign-common4 ➡️  gz-common5

- graphics/include/gz/common/SubMesh.hh
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
- graphics/src/VHACD/VHACD.h
Port gz-common5 to main
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common5
> Merge 5 -> main

- CMakeLists.txt
- Changelog.md
- README.md
Preparation for 6.0.0~pre1 release.
Comparison to 5.6.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.6.0...ionic_changelog
> Update Changelog, README and prepare for gz-common6.0.0~pre1 release

- examples/console.cc
- graphics/src/SVGLoader.cc
Port gz-common6 to main
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common6
This applies https://github.com/gazebosim/gz-common/pull/649 fix to gz-common-main ([reference build](https://build.osrfoundation.org/job/gz_common-ci-main-noble-amd64/52/consoleFull))
> 6 :arrow_right: main

- include/gz/common/Battery.hh
- profiler/include/gz/common/Profiler.hh
Fixes https://github.com/gazebosim/gz-common/issues/671#issuecomment-2838877654
> Added missing includes

- .github/workflows/ci.yml
- Changelog.md
- events/include/gz/common/Event.hh
- graphics/include/gz/common/SubMesh.hh
- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
- include/gz/common/Battery.hh
- include/gz/common/Console.hh
- profiler/include/gz/common/Profiler.hh
- test/performance/logging.cc
- testing/include/gz/common/testing/detail/AutoLogFixture.hh
Port `gz-common6 ` ➡️  `main`
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common6
> Merge gz-common6 ➡️  main

- .github/ci/packages.apt
- .github/workflows/ci.yml
- .github/workflows/macos.yml
- CMakeLists.txt
- av/src/CMakeLists.txt
- events/src/CMakeLists.txt
- examples/CMakeLists.txt
- geospatial/src/CMakeLists.txt
- graphics/src/CMakeLists.txt
- io/src/CMakeLists.txt
- package.xml
- profiler/src/CMakeLists.txt
- src/CMakeLists.txt
- test/integration/CMakeLists.txt
- test/performance/CMakeLists.txt
- tutorials/profiler.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
> Bump gz-cmake and others in jetty

- .github/workflows/bazel.yml
- .github/workflows/ci.bazelrc
Adds a new githhub action to run bazel build 
> Add CI support for bzlmod

- BUILD.bazel
- MODULE.bazel
- events/BUILD.bazel
- geospatial/BUILD.bazel
- graphics/BUILD.bazel
- io/BUILD.bazel
- profiler/BUILD.bazel
- test/BUILD.bazel
- testing/BUILD.bazel
Fixes missing layering check dependencies found with 
```
bazel build --action_env=CC=/usr/bin/clang ...
```
I also formatted the BUILD files manually with the VSCode bazel formatter.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> Bazel layering check fixes with clang

- Changelog.md
- graphics/src/AssimpLoader.cc
Port `gz-common5 ` ➡️  `gz-common6`
Branch comparison: https://github.com/gazebosim/gz-common/compare/gz-common6...gz-common5
> Merge gz-common5 ➡️  gz-common6

- CMakeLists.txt
Preparation for 7.0.0 release.
Comparison to 7.0.0-pre2: https://github.com/gazebosim/gz-common/compare/gz-common7_7.0.0-pre2...gz-common7
> Prepare for 7.0.0 Release
