gazebosim/gz-common

- Changelog.md
- graphics/src/ColladaLoader.cc
- graphics/src/ColladaLoader_TEST.cc
- test/data/box_opaque.dae
When loading `<transparent>` tag in our current implementation, we use a transparency value of 0.0 if `<transparency>` does not tag exist. But according to collada 1.5 spec chapter 7-6, page 250:
```
If <transparency> does not exist then it has no effect on the equation’s result. This is equivalent
to a factor that is 1.0: 
```
This causes some meshes to be transparent, see  ignitionrobotics/ign-rendering#89. This PR fixes the default <transparency> value used in calculation.
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
> Fix ColladaLoader loading <transparent> tag when <transparency> does not exist

- av/src/VideoEncoder.cc
- src/Filesystem.cc
- src/Util.cc
I had some failures on Windows related to these headers, but it turns  out that most of them are unused and probably they come from some old copy&paste, so they can be simply removed.
> Remove unused included headers

- av/include/ignition/common/AudioDecoder.hh
- av/src/AudioDecoder.cc
- av/src/AudioDecoder_TEST.cc
- av/src/CMakeLists.txt
I've updated the [unit tests](https://github.com/ignitionrobotics/ign-common/blob/audioDecoder_fix_adlarkin/av/src/AudioDecoder_TEST.cc) for the `AudioDecoder` class so that they compile and pass.
I also added a check in `AudioDecoder::SampleRate` to ensure that a null pointer is not de-referenced in case users call `AudioDecoder::SampleRate` before calling `AudioDecoder::SetFile`.
One question: In the case where users call `AudioDecoder::SampleRate` before calling `AudioDecoder::SetFile`, what should `AudioDecoder::SampleRate` return? I made `AudioDecoder::SampleRate` return `-1` in this case, because I figured that a negative sample rate implies that the decoder's current state is invalid. I anyone thinks there is a better value to return (for example, `0`), let me know, and I will …
> Fixed the AudioDecoder class

- tutorials/profiler.md
Use html instead of markdown image link to render image on ignition website
> Fix Profiler.md image link on ignition website

- profiler/src/RemoteryProfilerImpl.cc
- tutorials/profiler.md
Just some small fixes that I came across while going through this tutorial.  I also added a line more explicitly indicated to run `ign_remotery_vis` for Ignition libraries as it wasn't immediately clear to me how to open the browser window when profiling Ignition libraries
Signed-off-by: John Shepherd <john@openrobotics.org>
> Small Remotery tutorials fixes

- graphics/src/Animation.cc
Simple fix but took awhile to find and I think deserves some explanation as well as some tools I used that can be used in the future for memory profiling (possibly this part deserves its own tutorial or guide).
It was discovered that there was a significant memory leak in any ign-gazebo examples involving actors.  I used a project called [mem-usage-ui](https://github.com/parikls/mem_usage_ui) which was very simple yet effective in being able to visually confirm the existence of memory leaks.  The output from the actor example that was experiencing serious leakage is as follows: 
It can be seen that the memory leakage grew by about 100Mb in just one minute, if left for 15-20 minutes, this could crash the computer.  Using [heaptrack](https://github.com/KDE/heaptrack) or `valgrind` didn't …
> Fix trajectory info memory leak

- src/URI.cc
Ever since the addition of fuel world support, we've started to check the passed in file string.  In order to check for a valid URI link, we've been using `common::URI` ([here](https://github.com/ignitionrobotics/ign-gazebo/blob/master/src/Server.cc#L155)) which prints a warning message if the URI is not a correctly formatted URI.  Since we are using this class to check for a valid URI, the warning message removed in this PR prints for every non-valid URI file which is quite misleading.
Signed-off-by: John Shepherd <john@openrobotics.org>
> Remove invalid URI warning

- .github/ci-bionic/after_make.sh
- CMakeLists.txt
- include/ignition/common/Time.hh
- include/ignition/common/Timer.hh
- include/ignition/common/WorkerPool.hh
- src/CMakeLists.txt
- src/Time.cc
- src/Time_TEST.cc
- src/Timer.cc
- src/WorkerPool.cc
- src/WorkerPool_TEST.cc
This PR is part of this issue https://github.com/ignitionrobotics/ign-common/issues/61. The idea it's to deprecate the class `common::Time` in favor of `std::chrono`.
This two functions convert from `time_point` to seconds and nanoseconds and viceversa.
> Deprecated common:Time

- graphics/src/Material.cc
- graphics/src/Material_TEST.cc
Resolves https://github.com/ignitionrobotics/ign-gazebo/issues/343
Signed-off-by: John Shepherd <john@openrobotics.org>
> [ign-common3] Support fuel URLs for textures

- examples/CMakeLists.txt
- examples/README.md
- examples/console.cc
The motivation was to test this issue: https://github.com/ignitionrobotics/ign-common/issues/6
Also added a README to all examples.
I think we should consider putting each example into its own directory so they're self-contained. A new user might not necessarily know how to split them, especially as they get more complex.
> Add Console example

- .github/workflows/ci.yml
- .github/workflows/pr-collection-labeler.yml
- .github/workflows/triage.yml
Our GitHub actions haven't been running correctly for forks. This should fix all of them:
CI only on `push` means that PRs from forks aren't tested. Adding `pull_request` fixes forks, with the downside of triggering duplicated jobs for PRs coming from branches in this repo.
Also removed the codecov token for the Focal builds because we only need to upload coverage reports once, and this causes failures sometimes.
Resolves https://github.com/ignition-tooling/pr-collection-labeler/issues/4.
Uses the new [pull_request_target event](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).
Tested here: https://github.com/ignitionrobotics/testing/pull/14
Like above, uses the new [pull_request_target …
> [ign-common3] Improve fork experience

- examples/CMakeLists.txt
- include/ignition/common/StringUtils.hh
- src/Filesystem_TEST.cc
- src/StringUtils.cc
- src/StringUtils_TEST.cc
- src/SystemPaths_TEST.cc
A few things that I found when doing the forward port
1. Use variables in the examples `CMakeLists.txt` file to keep things from breaking across ports
2. Add a string "Join" function for convenience.
3. Replace all `getenv`, `setenv`, `putenv`, `unsetenv` with Ignition functionality.
> [ign-common3] Miscellaneous Cleanups

- av/src/Video.cc
Just copying from VideoEncoder so that Video class can be used standalone and `ignition::common::load()` doesn't need to be called from downstream code.
> Call ignition::common::load() from Video constructor

- av/include/ignition/common/Video.hh
- av/src/Video.cc
- test/integration/CMakeLists.txt
- test/integration/encoder_timing.cc
Test that verifies video encoder timing, which uses [VideoEncoder](https://github.com/ignitionrobotics/ign-common/blob/ign-common3/av/src/VideoEncoder.cc) to encode several frames to a video file and verifies the duration using the [Video](https://github.com/ignitionrobotics/ign-common/blob/encoder_timing_test/av/src/Video.cc) class with a new `Duration()` function.
> Video encoder timing test

- CMakeLists.txt
- src/CMakeLists.txt
- src/WorkerPool_TEST.cc
These two have a history of turning builds red, and already have tracking issues:
* #52 
* #53 
They will still compile, just not run on non-Linux platforms.
> ci: remove two known flaky tests

- CMakeLists.txt
Fortunately now in 2020 we have package managers on Windows, so at least giving an option to use an external TinyXML2 also on Windows make sense. : )
> Do not hardcode USE_EXTERNAL_TINYXML2 to OFF on Windows

- av/src/VideoEncoder.cc
I've played around with the video encoder and found (and fixed) the following little issues.
1. If you try to encode a video and supply a zero timestamp as the time of the first frame, it gets skipped.
1. Reset() did not reset timeStart and timePrev. Reset of timeStart is not technically needed, because Start() would correctly set it correctly based on the reset-ted value of frameCount. However, resetting it doesn't hurt anything. On the other hand, timePrev remained at its last value before Reset() call, which might lead to skipping the first frame of another video recording.
> Little fixes for video encoder

- test/integration/CMakeLists.txt
Disable the encoder integration test, which depends on the `av` component, which is currently not building on Windows.
I originally wanted to check for the `av` target first via:
```
if (NOT TARGET ${PROJECT_LIBRARY_TARGET_NAME}-av)
list(REMOVE_ITEM tests encoder_timing.cc)
endif()
```
But because integration tests are configured _before_ components, those targets don't exist yet.  I'm not sure if this could be considered a bug in ign-cmake.
> Disable AV integration test when component not available

- av/include/ignition/common/Video.hh
- av/src/Video.cc
- av/src/VideoEncoder.cc
- test/integration/CMakeLists.txt
- test/integration/encoder_timing.cc
The video encoder timing is incorrect when the source that's being encoded runs at a dynamic / slower FPS than the default video encoding rate (25 FPS). In ignition gazebo, this often happens when recording simulations with fluctuating GUI FPS (e.g. due to objects loading and unloading or complex scene), resulting in videos that have a shorter duration than expected.
More info:
The main cause of the problem is from setting the frame number associated with an input frame to be encoded. When a new frame arrives and is ready to be encoded, the frame is appended to the video by always setting it's frame number to frame count + 1. However, if the frame arrives late, e.g. several seconds late, the frame number should not just be incremented by 1 but a larger number (depending on how late the …
> Fix video encoder timing

- graphics/include/ignition/common/ColladaExporter.hh
- graphics/src/ColladaExporter.cc
- graphics/src/ColladaExporter_TEST.cc
Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>
This adds transformation matrixes to nodes con collada files when exporting
Connects to ignitionrobotics/ign-gazebo#307
> Add transformation matrix to ColladaExport

- Migration.md
- include/ignition/common/Util.hh
HOMEPATH alone is a pretty wicked concept. For its use to make sense, it has to be joined with HOMEDRIVE, because HOMEPATH is a path relative to HOMEDRIVE. So when you lookup just env("HOMEPATH") and use it as a file path, it gets resolved relative to any random drive letter that currently happens to be in CWD. I guess this could not be the inteded behavior.
USERPROFILE, on the other hand, contains the full absolute path to the user's home directory.
I looked through most libraries in github.com/ignitionrobotics, and none seemed to use IGN_HOMEDIR in a way that would assume the previous (wrong) value on Windows.
I don't consider this change a API or ABI break (the only thing it could break is already broken code :) ). However, as it is a change of a macro definition, it would need a …
> Fix IGN_HOMEDIR on Windows

- av/src/AudioDecoder_TEST.cc
- av/src/VideoEncoder.cc
- av/src/VideoEncoder_TEST.cc
- test/integration/encoder_timing.cc
I believe that these were introduced by changes in the Windows hosts, allowing the `av` component to be built and tested, so not necessarily a regression.
> Fix Windows AV CI warnings and test failures

- graphics/include/ignition/common/Material.hh
- graphics/src/Material.cc
- graphics/src/Material_TEST.cc
This PR is part of the effort to avoid z-fighting between coplanar meshes. 
Related with https://github.com/ignitionrobotics/ign-rendering/pull/188
> Added render order to material class

- graphics/src/Pbr.cc
Caught with Address Sanitizer. Acording to ASAN, Pbr.MoveCopy test
would allocate PbrPrivate on Pbr_TEST.cc:177 and leak on
Pbr_TEST.cc:178.
> Fix memory leak in Pbr.cc

- CMakeLists.txt
- Changelog.md
Comparison to 3.9.0: https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.9.0...ign-common3
It looks like none of the open PRs are close to getting in.
Needed to unblock https://github.com/ignitionrobotics/ign-rendering/pull/188
> ⬆️  3.10.0

- graphics/include/ignition/common/Material.hh
- graphics/src/ColladaExporter.cc
Collada considers an object to be transparent when the `<transparent>` value is 0 instead of 1.
This resolves: https://github.com/ignitionrobotics/ign-gazebo/pull/474#discussion_r547456437
> Collada transparency is opposite.

- README.md
- tutorials.md.in
- tutorials/install.md
- tutorials/profiler.md
Partially addresses https://github.com/ignitionrobotics/docs/issues/117 and https://github.com/ignitionrobotics/docs/issues/14#issuecomment-750431388 .
- Adds Windows binary and from source install instructions for https://github.com/ignitionrobotics/docs/issues/117 .
For some reason, I didn't encounter the compilation error @Jshep1 mentioned here https://github.com/ignitionrobotics/docs/issues/96#issuecomment-742096017 .
My steps are slightly different, as necessitated by these per-package installation tutorials.
John built everything from source using `colcon`.
I did `conda-forge` binary install for `ign-cmake` and `ign-math`, and then pure `cmake`.
Not sure if that makes the difference or I'm missing something.
- Moves installation in README to a new installation tutorial page for …
> Add Windows installation; move installation in README to tutorial

- graphics/include/ignition/common/MeshManager.hh
- graphics/src/MeshManager.cc
- graphics/src/SubMesh_TEST.cc
Related with this issue https://github.com/ignitionrobotics/ign-common/issues/140
> Added capsule mesh

- av/src/AudioDecoder_TEST.cc
- av/src/CMakeLists.txt
- av/src/VideoEncoder.cc
- av/src/VideoEncoder_TEST.cc
- graphics/src/CMakeLists.txt
- src/Filesystem_TEST.cc
An attempt at fixing https://github.com/ignitionrobotics/ign-common/issues/148.
The test changes are minimal, I recommend the view ignoring whitespace changes:
* Make test verbose
* Create `video` within a scope, so we can check that it deletes all temp files on destruction
* Output file paths in case the tests fail
The change that I hope will fix it is the use of `common::removeFile` instead of `std::remove`.
> Disable failing VideoEncoder and Audioecoder tests on Windows

- include/ignition/common/FlagSet.hh
- src/FlagSet_TEST.cc
This class helps managing a set of flags that are defined as a C++11 enum class.
Adapted from https://github.com/mrts/flag-set-cpp (MIT license, compatible with Apache 2.0).
I have a use for this class in my next PR (not yet published as it needs polishing). But I think it might be generally useful to have a canonical way to work with flag sets.
> Added FlagSet utility class

- graphics/src/ColladaExporter.cc
Using the ColladaExporter can flood the console with warnings like the following:
```
[Wrn] [SubMesh.cc:478] Multiple texture coordinate sets exist in submesh: WallPlaster. Checking first set with index: 0
```
This happens when a mesh has multiple texture coordinates. The ColladaExporter can prevent this by using the SubMesh function calls that specify which texture coordinate set to use.
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers
> Prevent console spam when exporting a mesh with multiple texture coordinates

- tutorials/hw-encoding.md
Fixing the Markdown syntax in the tutorial added in #169. I first thought it would get fixed by addressing ignitionrobotics/docs#145, but that showed to be a wontfix, so I'm fixing the syntax here.
> Fix markdown in tutorial

- Migration.md
- include/ignition/common/SystemPaths.hh
- include/ignition/common/URI.hh
- src/SystemPaths.cc
- src/SystemPaths_TEST.cc
- src/URI.cc
- src/URI_TEST.cc
While working on https://github.com/ignition-tooling/release-tools/issues/361, I noticed that the changes in the URI introduced in `ign-common4` were very disruptive, see https://github.com/ignitionrobotics/ign-fuel-tools/pull/163#issuecomment-768050613.
This is a proposal to reduce the impact of these changes and maintain support for the "URI" format that is widespread in the ecosystem (`model://` / `package://`).  Another goal of this PR is to make the changes more evident to downstream users through deprecation warnings.
Because there was no concept of "authority" up to `ign-common3`, it's safe to assume that users are currently embedding the authority into the path. This PR deprecates `URI::Path()` to hint to the user that something has changed and adds an alternative function, …
> Restore support for model:// URIs

- profiler/src/CMakeLists.txt
- profiler/src/Remotery/ign_remotery_vis.in
- tutorials/profiler.md
Fixes issue #167
Fixes issue #82 
This makes the profiler script get installed in a versioned subdirectory, which will enable side-by-side installs.
In this case, it follows along with our CLI executable strategy and installs to `install/lib/ignition/ignition-common4/ign_remotery_vis`
This additionally makes the profiler script relocatable by removing absolute paths from the CMake configuration process.
[contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
[test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers
> Install the profiler in a version-safe manner

- test/integration/video_encoder.cc
Fixes #180
The difference on that expectation for all ARM builds (arm64 and armhf) were exactly 1.86, so I think relaxing the tolerance to 2.0 should fix them.
I haven't looked closely enough at #125, but quickly looking at the test this seems like a reasonable solution to me.
CC @peci1 
> Relax expectation so encoder test passes on ARM

- graphics/include/ignition/common/MeshManager.hh
- graphics/src/MeshManager.cc
- graphics/src/SubMesh_TEST.cc
The capsule code was using Y-up, but Ignition uses Z-up. In particular, see the capsule description on [Ignition Math](https://github.com/ignitionrobotics/ign-math/blob/b84710d4fb05c953a80759b5cb6599b7a07d0df0/include/ignition/math/Capsule.hh#L37-L40) and on [SDFormat](https://github.com/osrf/sdformat/blob/20310281c555767a6df39a98fb3a4f1d677faf96/sdf/1.8/capsule_shape.sdf#L7).
Before | After
-- | --
> Rotate capsule to Z-up

- graphics/src/Skeleton.cc
Actors using BVH animations have been crashing `ign-gazebo`, probably since #136, see https://github.com/ignitionrobotics/ign-common/pull/136#issuecomment-805449865.
The problem is that we were creating a temporary `Skeleton`, getting a pointer to its animation, and then deleting the original skeleton. Now that the skeleton is properly destroyed, we also destroy that pointer. The solution is to make a copy so we can keep ownership.
This needs to be backported to `ign-common3`, I'm targeting `main` so we can get it into Edifice's first release. I believe this is a critical bug fix.
@adlarkin , I believe you've been looking into this. Maybe you can see if this works?
> Fix crash when using BVH animations

- av/src/AudioDecoder.cc
- av/src/AudioDecoder_TEST.cc
Since `_outBuffer` is given to `realloc()` in the middle of `AudioDecoder::Decode()` we use malloc/free for consistency.
`bazel test --copt="-fsanitize=address" --linkopt="-fsanitize=address" //ign_common/av:AudioDecoder_TEST` would still fail due to a read heap-buffer-overflow. I think it has to with the fact that FFmpeg has both packed and planar sample format:
https://ffmpeg.org/doxygen/trunk/group__lavu__sampfmts.html
The current code works for packed format but would read past allocated buffer in planar format case where two channels are stored in `data[0]` and `data[1]` respectively.
> Use matching malloc/free for AudioDecoder.

- CMakeLists.txt
- Changelog.md
- examples/CMakeLists.txt
- tutorials/profiler.md
Branch `ign-common4` has been created for the Edifice release and 4.0.0 released from that.
The `main` branch now corresponds to version 5.0.0~pre1, and nightlies will soon be created from this branch.
https://github.com/ignition-tooling/release-tools/issues/421
> Bump main to 5.0.0~pre1

- README.md
The installation tutorial is not available in 3.9 docs, so I changed the link to 4.0 where it can be found.
> Fixed tutorial link

- CMakeLists.txt
- Changelog.md
Preparation for <3.12.0>release.
Comparison to <3.11.1>: https://github.com/ignitionrobotics/ign-common/compare/ignition-common3_3.11.1...ign-common3
Needed by https://github.com/ignitionrobotics/ign-launch/pull/97
> Prepare for 3.12.0 release

- include/ignition/common/Util.hh
@ahcorde I just checked this with compiler explorer, this should be sufficient to clear the warning.
> Fix C4307 warning

- graphics/src/ColladaLoader.cc
Relative image on WIndows was not working because we were using only the UNIX like separator
Related to this PR https://github.com/ignitionrobotics/ign-rendering/pull/291
> Fixed colladaLoader on Windows

- graphics/src/ColladaExporter.cc
- graphics/src/ColladaExporter_TEST.cc
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
Fixes #202 
This PR removes the ColladaExporter constraint on the path to include "meshes" in their names to be exported. As per discussion in #202 this check might be related to code from Ignition Gazebo and may not be needed now.
> Remove ColladaExporter path constraint

- graphics/include/ignition/common/Image.hh
- graphics/src/Image_TEST.cc
I think that we should generally avoid raw `new` and `delete` calls in code going forward.  In this case, the test was also allocating memory without deallocating.
I replaced heap allocations with `std::vector<T>` where it made sense.
> Remove raw new/delete calls from #205

- graphics/include/ignition/common/Image.hh
- graphics/src/Image_TEST.cc
Used by https://github.com/ignitionrobotics/ign-gui/pull/212 and https://github.com/ignitionrobotics/ign-launch/pull/112
Added a generic helper function for converting single channel image data, e.g. thermal and depth images, to an RGB image. This is intended to be used for visualization. Optional arguments can be specified to tweak the visualization. 
The corresponding PRs in ign gui updates the Image Display to use this new function: https://github.com/ignitionrobotics/ign-gui/pull/212
You can test this together with that PR by running the `sensors_demo.sdf` world to see the visualization in Image Display
> Add function to convert single channel image data to RGB image

- BUILD.bazel
- CMakeLists.txt
- Changelog.md
Preparation for 3.13.0 release.
Comparison to <x.y.z>: https://github.com/ignitionrobotics/<REPO>/compare/ignition-common3_3.12.0...ign-common3
Needed by <PR(s)>
> Prepare for 3.13.0 release

- graphics/include/ignition/common/SkeletonAnimation.hh
- graphics/src/Skeleton.cc
- graphics/src/SkeletonAnimation.cc
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
Related to https://github.com/ignitionrobotics/ign-gazebo/issues/647
This is a backport of #188. Once this is merged, we should no longer see actors crash at launch (the `ign-common3` branch applies to both Citadel and Dome).
To test this, run `ign gazebo -r actor.sdf` and make sure no crash occurs.
> Backport #188: Fix crash when using BVH animations

- src/Filesystem.cc
- src/Filesystem_TEST.cc
The `joinPaths` function would remove trailing slashes from the function arguments. This can cause downstream applications, like fuel tools using libzip, to treat a directory as a file.
> Fix join paths to remove duplicate separators

- graphics/src/ColladaLoader.cc
- graphics/src/ColladaLoader_TEST.cc
- test/data/multiple_texture_coordinates_triangle.dae
When loading texture coordinates, there was an assumption in the ColladaLoader that the `offset` values (which specify the index in which the uv coordinates should be read from) need to be unique. This is found that be incorrect assumption after looking at Collada 1.5 spec ([link](https://www.khronos.org/files/collada_spec_1_5.pdf) to pdf. There is an example on page 89). 
This PR updates the loader to support loading duplicate `offset` values.
One way to test this is to use Edifice. You'll need to use this ign-common4 branch: `collada_texcoord_offset_4`, and launch a world in ign-gazebo with this [model](https://github.com/ignitionrobotics/ign-common/files/6401985/WheelChairUnfolded.zip) (zip file). Without this change, the light map is rendered incorrectly on the model and it'll appear …
>  Fix loading collada files with multiple texcoord sets using the same offset

- src/Filesystem.cc
- src/Filesystem_TEST.cc
PR #209 broke a different part of fuel-tools, this time in [ModelIdentifier](https://github.com/ignitionrobotics/ign-fuel-tools/blob/ign-fuel-tools5/src/ModelIdentifier.cc#L146). Strings with `https://server` would become `https:/server`. Note the missing second slash. This is an invalid URI.
> Fix join paths again

- CMakeLists.txt
- test/CMakeLists.txt
> Also set gtest's standard to C++11

- graphics/include/ignition/common/ColladaExporter.hh
- graphics/src/ColladaExporter.cc
- graphics/src/ColladaExporter_TEST.cc
Closes [#901](https://github.com/ignitionrobotics/ign-gazebo/issues/901)
[Downstream PR](https://github.com/ignitionrobotics/ign-gazebo/pull/912)
- Exports lights for the collada world exporter. Based off the [collada 1.4 spec](https://www.khronos.org/files/collada_spec_1_4.pdf)
- Test added for collada exporter exporting lights
run `./build/ignition-common4/bin/UNIT_ColladaExporter_TEST`
> Export lights to dae

- graphics/src/Image.cc
Just a simple fix for a really weird compilation error. Shouldn't have seen it, but saw it, so created a tiny PR
> Add cstring for `std::memcpy`

- events/include/ignition/common/Event.hh
- events/src/Event_TEST.cc
Fixes https://github.com/ignitionrobotics/ign-gazebo/issues/906
A segfault occurs in the destructor of `common::Connection` if the `common::Event` its associated with has already been deleted. This patch clears the `event` pointer of `common::Connection` when the associated `common::Event` is deleted. 
Another issue mentioned in https://github.com/ignitionrobotics/ign-gazebo/issues/906 is that the destructor of `std::function` crashes if the function it points to is from a shared library that has been unloaded. This is fixed by invoking the destructor as soon as `common:EventT::Disconnect` is called via `common::Connection::~Connection` since that's likely to be right before the shared library containing the `common::Connection` is unloaded.
**Note to maintainers**: Remember to use …
> Fix segfault caused by destruction order of Event and Connection

- av/src/VideoEncoder_TEST.cc
The same typo is also in `ign-common4` and `main` branches.
> Fix a typo in VideoEncoder_TEST.

- include/ignition/common/Console.hh
- src/Console.cc
- src/Util.cc
- test/performance/logging.cc
I ran the `PERFORMANCE_logging` test under TSAN and found more data races. One deals with `std::localtime`, which apparently is not thread-safe as it returns a pointer to an internal static object. The others deal with the fact that the `Buffer` class has a `std::string` member inherited from `std::stringbuf` and it (the string) also needs synchronization.
I put the mutex as a member in `Buffer` since it's needed in two functions. This means that each console stream (i.e. ignmsg, ignwarn, etc) gets its own mutex. It turns out we don't really need to synchronize on the `stdout` or `stderr` 
According to https://timsong-cpp.github.io/cppwp/n3337/iostream.objects#overview-4, accessing `stdout` or `stderr` from multiple threads should not cause a data race, so we don't need a global mutex for …
> Suggestion to #227: More data race fixes

- graphics/src/Image.cc
Image was calling SwapRedBlue unconditionally based on compile-time
values.
That meant that greyscale images would try to swap Red and Blue
channels, but there is only one channel. This resulted in artifacts on
the final image as well as memory corruption as the last pixels would be
swapped against out of bound regions.
Additionally, there were several instances where FIBITMAP handles were
leaking.
Signed-off-by: Matias N. Goldberg <dark_sylinc@yahoo.com.ar>
No ticket was issued.
How to repro: Just load a greyscale 8-bit image and use a tool like valgrind or ASAN to see the corruption.
The memory leaks will be hard to spot though.
**It is possible this fix should be backported to older releases**
> Fix memory corruption & leaks in Image

- include/ignition/common/TempDirectory.hh
- src/CMakeLists.txt
- src/TempDirectory.cc
Fixes https://github.com/ignition-tooling/gazebodistro/pull/45
TempDirectory incorrectly added the ign-utils1 dependency, this roills that back.
> Remove ign-utils from TempDirectory

- README.md
Update the Contributing link in the README to point directly to ignitionrobotics.org, since it currently points to an ign-gazebo page that verbally redirects, so this cuts out the middle-man.
> README: link directly to Contributing page

- test/integration/CMakeLists.txt
`${}` gives the result in string so something like `colcon build --merge-install --packages-up-to ignition-common4 --cmake-args '-DSKIP_av=true'` might not work as expected.
> Use direct evaluation for SKIP_av.

- profiler/src/CMakeLists.txt
Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>
While I was testing the ign-gazebo python interface on macos I noticed that some symbols are missing. This should fix it.
There are some other which are not included, for example: `RMT_USE_D3D11` or `RMT_USE_OPENGL`. Should we need to remove these ones or add the `target_compile_definitions`?
> Fixed macos symbol in common::profiler

- graphics/src/OBJLoader.cc
Normal vectors that are not normalized might cause incorrect rendering results.
> Normalize normal vectors from OBJ.

- .github/workflows/ci.yml
~~Testing CI update to Jammy.~~ It doesn't work yet, see https://github.com/ignition-tooling/release-tools/issues/566
So this PR just drops Bionic to unblock #267.
Note that even if `ign-common5` doesn't go into Garden (discussion in https://github.com/ignition-tooling/release-tools/issues/567, it will end up in a future version that doesn't support Bionic.
See CI results.
> ign-common5: drop Bionic

- profiler/src/CMakeLists.txt
Closes #271
We are installing the profiler visualizer binary under the standard library path which is something that does not fit well according to the [FHR](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec). libexec seems a better place for them.
> 4.7.1. Purpose
> /usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.
> Use libexec to install binary remotery_vis

- CMakeLists.txt
- include/ignition/common/Battery.hh
- include/ignition/common/Filesystem.hh
- include/ignition/common/SystemPaths.hh
- include/ignition/common/TempDirectory.hh
- include/ignition/common/URI.hh
- include/ignition/common/WorkerPool.hh
- src/Battery.cc
- src/CMakeLists.txt
- src/FilesystemBoost.cc
- src/SystemPaths.cc
- src/TempDirectory.cc
- src/URI.cc
- src/URI_TEST.cc
- src/WorkerPool.cc
Since we can add a dependency on `ign-utils1`, update to use the `ImplPtr` pattern instead of `std::unique_ptr` where relevant.
> Use ImplPtr where relevant

- src/URI.cc
- src/URI_TEST.cc
Discovered in #274.
The issue is that the `URIPath::Implementation` struct has a `trailingSlash` member: https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI.cc#L54-L73
The originally written copy-assignment operator doesn't copy this member:
https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI.cc#L586-L591
And the test exercises this copy-assignment: 
https://github.com/ignitionrobotics/ign-common/blob/ign-common4/src/URI_TEST.cc#L890-L894
In this case, `ImplPtr` has shown that the previous behavior is actually a bug, and we should fix it in previous versions.
> Fix bug in URIPath assignment operator

- graphics/include/ignition/common/ImageHeightmap.hh
- graphics/src/ImageHeightmap.cc
- graphics/src/ImageHeightmap_TEST.cc
Fixes #265 
Assuming [PixelFormat](https://github.com/ignitionrobotics/ign-common/blob/ign-common4/graphics/src/Image.cc#L516) function returns a correct value this should allow supporting 8, 16 and 32 bit heightmaps. Having said that I tried to test this with a hand constructed 16bit version of city_terrain.jpg (just multiplied each value by 256 didn't want to spend so much time on that), ~the PixelFormat function is still returning `L_INT8` (which is the same as the 8 bit version) causing the spikes. This needs to be resolved as well. I'll try to have a deeper look on why we aren't getting correct return from this function.~ That was my bad that I left the extension of 16 bit image as .jpg (should have been png), it's now throwing a very suppressive error messages starting with `[Err] …
> Support 16 bit heightmaps

- graphics/src/ColladaLoader.cc
If a collada file has defined normals but these are empty, then Ignition will crash. This should fix this crash
> Fixed crash when a Collada file has an empty normal vector

- .github/ci/packages.apt
- BUILD.bazel
- CMakeLists.txt
- av/BUILD.bazel
- configure.bat
- events/BUILD.bazel
- graphics/BUILD.bazel
- graphics/include/ignition/common/Image.hh
- graphics/src/ColladaExporter.cc
- graphics/src/ColladaLoader.cc
- graphics/src/MeshManager.cc
- graphics/src/NodeTransform.cc
- graphics/src/SVGLoader.cc
- profiler/BUILD.bazel
- src/Filesystem.cc
See https://github.com/ignition-tooling/release-tools/issues/574
> Bumps in garden: use ignition-math7

- .github/workflows/macos.yml
Part of https://github.com/ignition-tooling/release-tools/issues/564
Copy changes for checking out matching branches in macOS workflow from https://github.com/ignitionrobotics/sdformat/pull/803
> Try to checkout matching branch in macos workflow

- graphics/src/Image.cc
Fixes ignitionrobotics/ign-gui#341 .
#240 contains a lot of fixes for Image, but was only merged to ign-common4. This PR backports it into 3.
> Backport of #240 to fix memory leaks in Image.

- .github/workflows/ci.yml
When we dropped Bionic on #270 , we should have enabled test coverage for Focal. Right now we have no coverage reports on `main` :grimacing: 
> Upload coverage for Focal builds

- Migration.md
- geospatial/include/ignition/common/geospatial/Dem.hh
- geospatial/include/ignition/common/geospatial/HeightmapData.hh
- geospatial/include/ignition/common/geospatial/ImageHeightmap.hh
- geospatial/src/Dem.cc
- geospatial/src/Dem_TEST.cc
- geospatial/src/ImageHeightmap.cc
- geospatial/src/ImageHeightmap_TEST.cc
Follow-up to #267, connected to https://github.com/ignition-release/ign-common5-release/pull/4
This simplifies the logic required for packaging by putting all the geospatial header files in a subfolder. We haven't done this for the other ing-common components, but now is an easy time to do it for geospatial since we are already breaking things with this component.
> Move geospatial headers to subfolder

- src/URI.cc
Uncovered in the process of testing #301.
Before this fix:
- Expected behavior: Tests build and run when -D_GLIBCXX_ASSERTIONS is set
- Actual behavior: Test aborts due to out-of-bounds access
Steps to reproduce
```
git checkout ign-common4
CXXFLAGS=-D_GLIBCXX_ASSERTIONS cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
make -C build UNIT_URI_TEST
./build/bin/UNIT_URI_TEST
gdb -ex run ./build/bin/UNIT_URI_TEST
```
> Fix out-of-bound access in URI

- src/Filesystem.cc
Fixes #301
Before this fix:
- Expected behavior: Tests build and run when -D_GLIBCXX_ASSERTIONS is set
- Actual behavior: Test aborts due to out-of-bounds access
Steps to reproduce
```
git checkout ign-common4
CXXFLAGS=-D_GLIBCXX_ASSERTIONS cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
make -C build UNIT_Filesystem_TEST
./build/bin/UNIT_Filesystem_TEST
gdb -ex run ./build/bin/UNIT_Filesystem_TEST
```
> Fix out-of-bounds access in sanitizeSlashes

- Migration.md
- graphics/include/ignition/common/Image.hh
- graphics/src/Image.cc
Split out from #292
The `Image::Data`, `Image::RGBData`, and `Image::AvgColor` methods do not modify any object data but are not marked as `const`, which prevents other `const` methods from calling them. This changes API, so it must be done on the main branch.
> Image: make several methods const

- include/ignition/common/Filesystem.hh
- src/Filesystem.cc
- src/Filesystem_TEST.cc
Fixes #<NUMBER>
This PR adds an `isRelativePath` function to ign-common Filesystem.hh. It is a simple wrapper around `std::filesystem`.  The rationale for this is so we can remove `std::filesystem` from ign-gazebo as this is causing other issues such as https://github.com/ignition-tooling/release-tools/issues/639.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>
> Adds an `isRelativePath` to determine if path is relative

- events/include/ignition/common/Event.hh
- events/include/ignition/common/KeyEvent.hh
- events/include/ignition/common/MouseEvent.hh
- events/src/Event.cc
- events/src/KeyEvent.cc
- events/src/MouseEvent.cc
There were two issues with the Events API:
1. There were several places where we were using `const primitive` arguments to functions. https://clang.llvm.org/extra/clang-tidy/checks/readability-avoid-const-params-in-decls.html
2. There were several places where we marked a `SetXXX` function as `const` where we mutated internal data, breaking const-correctness.
These are split in two commits for easier review.
> Miscellaneous cleanup of Events API

- .github/workflows/ci.yml
Part of https://github.com/ignition-tooling/release-tools/issues/566
Add GitHub workflow for Ubuntu 22.04 (Jammy)
> [ign-common4] Add CI support for Jammy

- src/Filesystem_TEST.cc
Verify the behavior of parentPath and basename in ign-common4 to assert that #308 is correct.
> Add some tests for parentPath/basename

- src/Filesystem.cc
- src/Filesystem_TEST.cc
As it turns out, separator's behavior was not matching the `ign-common5` behavior.  Passing an empty string should return the preferred separator for the operating system.  We were not currently testing for this.
> Fix filesystem::separator behavior

- profiler/src/RemoteryProfilerImpl.hh
Cleans up a clang12 warning.
```
In file included from /home/mjcarroll/workspaces/ign_garden/src/ign-common/profiler/src/RemoteryProfilerImpl.cc:20:
/home/mjcarroll/workspaces/ign_garden/src/ign-common/profiler/src/RemoteryProfilerImpl.hh:53:39: warning: class with destructor marked 'final' cannot be inherited from [-Wfinal-dtor-non-final-class]
public: ~RemoteryProfilerImpl() final;
^
/home/mjcarroll/workspaces/ign_garden/src/ign-common/profiler/src/RemoteryProfilerImpl.hh:47:11: note: mark 'ignition::common::RemoteryProfilerImpl' as 'final' to silence this warning
class RemoteryProfilerImpl: public ProfilerImpl
```
> Class with final destructor should be final

- av/src/AudioDecoder.cc
- av/src/AudioDecoder_TEST.cc
- av/src/Video.cc
- av/src/VideoEncoder.cc
Fixes #306
This PR fixes compilation against FFmpeg 5.0 . It has been tested by using the conda-forge build of ffmpeg 5.0 on Linux, in particular with this deps:
~~~
#
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aom                       3.3.0                h27087fc_1    conda-forge
binutils                  2.36.1               hdd6e379_2    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-compiler                1.4.1 …
> Fix compatibility with FFmpeg 5.0

- src/Console.cc
- test/integration/console.cc
Fixes #331 
Use `Console:log()` in Console.cc in order to support execution of the `ignLogInit` function after console out has occured.
> Fix issue 331

- testing/include/ignition/common/testing/BazelTestPaths.hh
- testing/include/ignition/common/testing/CMakeTestPaths.hh
- testing/include/ignition/common/testing/TestPaths.hh
- testing/include/ignition/common/testing/Utils.hh
Should fix Windows CI for #314 
> Fix visibility for Windows

- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
A typo in the following snippet was causing `materialIndex` to be accessed when did not contain a value.
```c++
if (this-dataPtr->materialIndex.has_value()) //  Note the `-` instead of `->` in `this-dataPtr`.
return this->dataPtr->materialIndex.value();
```
> Fix typo bug in MaterialIndex

- CMakeLists.txt
- av/src/AudioDecoder_TEST.cc
- av/src/CMakeLists.txt
- src/CMakeLists.txt
- src/Filesystem_TEST.cc
- src/TempDirectory_TEST.cc
- src/WorkerPool_TEST.cc
`ign-cmake` utilities are deprecated from Garden. We should use `ign-utils` instead.
This should help with 
* https://github.com/ignition-tooling/release-tools/issues/685
CI should pass.
> Use ign-utils instead of ign-cmake utilities

- src/Timer_TEST.cc
It's been a bit flaky, some CI machines are "too" fast.
> Make Timer_TEST more robust

- graphics/src/SVGLoader.cc
Warning is raised when compiling on Ubuntu Jammy using g++11.
```
/home/ijnek/ignition/garden/src/ign-common/graphics/src/SVGLoader.cc:584:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
584 |         while (i < count)
|                ~~^~~~~~~
/home/ijnek/ignition/garden/src/ign-common/graphics/src/SVGLoader.cc:602:7: note: here
602 |       case 'Z':
|       ^~~~
---
```
Simply add a break to the switch case statement as the fallthrough seems unintended.
> fix switch case fall through warning

- tutorials/profiler.md
Signed-off by: Onur Berk Tore otore19@ku.edu.tr
Adds full path for the profiler 
> Adds full path for the profiler executable

- graphics/src/AssimpLoader.cc
Previous version does not work if root node does not have a child (creates problems for simple meshes like avocado below.)
> Fix: Works when the root node doesnt have child

- Migration.md
- av/include/gz/common/VideoEncoder.hh
- av/src/CMakeLists.txt
- av/src/VideoEncoder.cc
- include/gz/common/SystemPaths.hh
- src/SystemPaths.cc
- src/SystemPaths_TEST.cc
- tutorials/hw-encoding.md
See: https://github.com/gazebo-tooling/release-tools/issues/734
> ign -> gz Environment Variable Migration : gz-common

- profiler/src/CMakeLists.txt
- profiler/src/Profiler_Remotery_TEST.cc
- profiler/src/RemoteryProfilerImpl.cc
See: https://github.com/gazebo-tooling/release-tools/issues/737
Fixes a buggy option
> ign -> gz Macro Migration : gz-common (2)

- include/ignition/common/Console.hh
- src/Console.cc
Some of the flaky tests in gz-sim are still caused by race conditions in `Console`, this time in the `FileLogger`.
This PR applies the same fix from #227 to `Console::FileLogger`. 
> Fix race condition in FileLogger

- src/SystemPaths.cc
If you are running gazebo in the same folder that a custom plugin is located, then you are able to find it. According with the comment I think this code is more appropriate.
> Fix FindSharedLibrary for relative plugin paths

- src/SystemPaths.cc
- src/SystemPaths_TEST.cc
While working on https://github.com/gazebosim/gz-sim/pull/1574, some tests were failing with error:
~~~
Start 43: UNIT_ign_TEST
43: Test command: C:\src\ign-gazebo\build\bin\UNIT_ign_TEST.exe "--gtest_output=xml:C:/src/ign-gazebo/build/test_results/UNIT_ign_TEST.xml"
43: Environment variables:
43:  IGN_CONFIG_PATH=C:/src/ign-gazebo/build/test/conf
43:  IGN_GAZEBO_SYSTEM_PLUGIN_PATH=C:/src/ign-gazebo/build/bin
43: Test timeout computed to be: 240
43: Running main() from C:\src\ign-gazebo\test\gtest\src\gtest_main.cc
43: [==========] Running 3 tests from 1 test suite.
43: [----------] Global test environment set-up.
43: [----------] 3 tests from CmdLine
43: [ RUN      ] CmdLine.Server
43: Running command [ C:/Users/STraversaro/AppData/Local/mambaforge/envs/igngaz/Library/bin/ign gazebo -s …
> Support absolute Windows paths with forward slashes in common::FindFile

- src/CMakeLists.txt
Follow up to
* https://github.com/gazebosim/gz-common/pull/90
* https://github.com/gazebosim/gz-common/pull/273
Just a left-over that I found.
> Remove deprecated include

- api.md.in
- tutorials.md.in
I ran `find . -name "*" -exec -i 's/IGN_DESIGNATION/GZ_DESIGNATION/g' {} \;` in order to make this repository compliant with https://github.com/gazebosim/gz-cmake/pull/282
> Change IGN_DESIGNATION to GZ_DESIGNATION

- av/src/AudioDecoder.cc
Closes #415
This bit of code is already protected by LIBAVFORMAT_VERSION_MAJOR >= 59, which had the `ch_layout.nb_channels` that is recommended to be used by their API: https://github.com/FFmpeg/FFmpeg/blob/d931554f668186729bf290ed9afa6e9a4417328b/libavcodec/avcodec.h#L1009-L1016
> Fix deprecation warning from new ffmpeg

- graphics/src/AssimpLoader.cc
- graphics/src/MeshManager.cc
Fixes #393 
This commit introduces the flip uv flag for unnessary y flip during addition of texture coordinates. Furthermore removes
an empty line.
> Introduces Flips UV flag, removes empty space

- av/src/AudioDecoder.cc
Port gz-common5 to ign-common3
Backports: 
* https://github.com/gazebosim/gz-common/pull/416
Branch comparison: https://github.com/gazebosim/gz-common/compare/ign-common3...Crola1702:Crola1702/5_to_3-2022_08_16
> Backport from 5 to 3 - Fix deprecation warning from new ffmpeg

- testing/include/gz/common/testing/AutoLogFixture.hh
Fixes issue brought up in comment here: https://github.com/gazebosim/gz-common/pull/411#issuecomment-1220892591
The header `AutoLogFixture.hh` is available to be used as part of a library or executable that links against `gtest`.  We don't want to introduce a hard dependency on `gtest` in `common::testing` for just this header, but it seems to annoy the ABI checker.
~~This adds a private include so that the gtest header may be resolved, even though downstream users of the `testing` component will never see it.~~
This puts the AutoLogFixture within a define guard `GTEST_API` to guarantee that gtest is available before using the autologfixture.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to …
> Fix ABI checker with testing module

- io/include/gz/common/DataFrame.hh
- io/src/DataFrame_TEST.cc
Fixes https://github.com/gazebosim/gz-common/issues/434
This patch fixes a minor issue introduced in #402. Namely, header row shouldn't be read in as numeric data. It also updates tests to identify this regression.
> Skip CSV header when reading DataFrame

- tutorials/install.md
From source installation of common5 on Windows according to the tutorial fails to build the geospatial component.
> Add gdal to prerequisites

- CMakeLists.txt
- Changelog.md
Preparation for 3.15.- release.
Comparison to 3.14.2: [https://github.com/gazebosim/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>](https://github.com/gazebosim/gz-common/compare/ignition-common3_3.14.2...ign-common3)
Needed by https://github.com/gazebosim/gz-fuel-tools/pull/285
> 3.15.0 release

- io/include/gz/common/DataFrame.hh
- io/src/DataFrame_TEST.cc
This is useful for when we perform visualization.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>
> Adds an API to retrieve keys.

- profiler/CMakeLists.txt
- profiler/include/gz/CMakeLists.txt
- profiler/include/gz/common/CMakeLists.txt
Fixes unstable 3.15.0 debbuild issue
Many of the 3.15.0 debbuilds were unstable:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=1053)](https://build.osrfoundation.org/job/ign-common3-debbuilder/1053/) https://build.osrfoundation.org/job/ign-common3-debbuilder/1053/
~~~
dh_missing: warning: usr/include/ignition/common3/CMakeLists.txt exists in debian/tmp but is not installed to anywhere
~~~
The `profiler` component was installing its `CMakeLists.txt` file, probably due to an issue with #418. This changes the `CMakeLists.txt` pattern to match the `events` component.
> Don't install CMakeLists.txt

- CMakeLists.txt
- io/src/CSVStreams.cc
ARM doesn't allow narrowing conversions inside `{}` initializers. See here: https://build.osrfoundation.org/job/gz-common5-debbuilder/786/consoleFull#3015109326ea37b8d-a6d4-40ae-8431-d90c018842af
> Fix arm builds

- CMakeLists.txt
- Changelog.md
Preparation for 5.2.1 release. This should fix the arm builds. Test done here: https://build.osrfoundation.org/job/gz-common5-debbuilder/797/
Comparison to 5.2.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.2.0...gz-common5
> 5.2.1 release

- graphics/src/MeshManager.cc
Fixes https://github.com/gazebosim/gz-sim/issues/1769
In #186 Capsule was updated to be z-up, however when merging forward the ign-gz changes, the logic was accidentally reverted.
> Fix Capsule mesh generation

- graphics/include/gz/common/SubMesh.hh
- graphics/src/Mesh_TEST.cc
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
This PR exposes vertex & index raw ptrs.
It is necessary to _significantly_ improve performance of Ogre2RayQuery.
It is up to caller to ensure this unsafe pointers are read properly and hence its usage is discouraged; only when necessary.
> Expose Vertex & Index raw ptrs for efficient reading

- CMakeLists.txt
- Changelog.md
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
Preparation for 5.3.0 release.
Comparison to 5.2.2: https://github.com/gazebosim/gz-common/compare/gz-common5_5.2.2...prepare_5.3.0
Needed by https://github.com/gazebosim/gz-rendering/pull/752
> Prepare for 5.3.0 release

- graphics/src/AssimpLoader.cc
Alternative to #478, it fixes the root cause of the issue that is undefined behavior due to access past the end of the array.
When the parsing function was written, the assumption was that the position keys array and the rotation keys array would be the same length, this proved to not be the case since they can have different lengths.
The root cause of the issue addressed through #478 was that the rotation key array only had one element while the position key array was much longer, hence we were accessing values past the end of the array which is undefined behavior and can cause all sorts of trouble to downstream users.
Other cases with other animations can cause NaN exceptions in OGRE2 that crash the whole application.
With this PR we iterate over the longest of the arrays (to make sure …
> Fix out of bounds access to rotation array in assimp loader

- graphics/src/AssimpLoader.cc
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>
Fixes #<NUMBER>
Fixed metalness/roughness in ASSIMP loader
These values are float not double that's why the return value were always bad.
> Fixed metalness/roughness in ASSIMP loader

- av/src/AudioDecoder.cc
- av/src/Video.cc
This is fixing the fact that in AVCodec version 6 and above, the `AV_CODEC_CAP_TRUNCATED` has been removed, and thus `gz-common` was not compiling.
> Fix for ffmpeg v6

- av/src/AudioDecoder.cc
- av/src/Video.cc
Fixes #503 
Backport #497 to `ign-common3` to fix a build failure with ffmpeg 6.0 on macOS.
**Note to maintainers**: Remember to use **Rebase-and-Merge**.
> Backport #497 to ign-common3: Fix for ffmpeg v6

- av/src/Video.cc
Port `ign-common4 ` ➡️  `gz-common5`
Branch comparison: https://github.com/gazebosim/gz-common/compare/gz-common5...ign-common4
> Merge ign-common4 ➡️  gz-common5

- graphics/src/Image.cc
Closes [`gz-sensors` issue 299](https://github.com/gazebosim/gz-sensors/issues/299) 
-  [x] Support  simulation for `BAYER_RGGB8` with `OGRE`
-  [x] Extend the functionality to support all bayer types with `OGRE`
-  [x] Extend the functionality to support with `OGRE2`
The functionality reads the user input and renders an RGB image, which is later converted into a single channel 8bit Bayer image using `ConvertRGBToBayer()` added to [`Utils.cc`](https://github.com/gazebosim/gz-rendering/blob/gz-rendering7/src/Utils.cc) inside `gz-rendering`.
* `gz-sensors` : Adds a switch case for `RGGB bayer format` inside `CameraSensor.cc` and passes the `R8G8B8` format to render the image.
* `gz-redering` : Adds `ConvertRGBToBayer()` to `Utils.cc`, modifies `OgreRenderTarget.cc` to call the conversion …
> Add support for bayer images to be saved in a directory

- CMakeLists.txt
- Changelog.md
Preparation for 5.4.0 release.
Comparison to 5.3.1: https://github.com/gazebosim/gz-common/compare/gz-common5_5.3.1...prepare_5.4.0
Needed by https://github.com/gazebosim/gz-rendering/pull/838
> Prepare for 5.4.0 release

- profiler/src/RemoteryProfilerImpl.hh
#512 fix done against `ign-common3`. (summary: missing `<cstdint>` header thrown on GCC 13.1.1)
cc @marcoag 
> Fix missing cstdint header in latest gcc build

- profiler/src/ProfilerImpl.hh
Building with GCC 13 will fail due to `uint32_t` in: https://github.com/gazebosim/gz-common/blob/ec86532d6910e8e9068bc9425fb4374fdd00cbc7/profiler/src/ProfilerImpl.hh#L56
This PR can (and should) be included in newer versions too.
> Include cstdint to build with GCC 13

- test/integration/CMakeLists.txt
Fixes #522 
This removes `mesh.cc` if the graphics component is not built either by being disabled by the user or from missing dependencies.
> Only build mesh integration tests if graphics libraries are built

- .github/workflows/macos.yml
Fix macOS actions build
Same as https://github.com/gazebosim/sdformat/pull/1271
Workaround to https://github.com/actions/setup-python/issues/577
> Fix Github Actions on macOS

- CMakeLists.txt
- Changelog.md
Preparation for 5.4.1 release.
Comparison to 5.4.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.4.0...gz-common5
> Prepare for 5.4.1 release

- graphics/src/AssimpLoader.cc
glb file packs the metalness and roughness maps (grayscale) in a single texture (in the R and G channels) and our Assimp loader splits them out into individual textures for use in gz-rendering. However, the texture data are written out incorrectly (rotated by 90 degrees). This PR fixes that logic.
For testing, I'm using the water bottle glb file from: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle. You can see a screenshot of what the water bottle supposed to look like in that page.
Here're screenshots in gazebo showing before and after the fix:
Before:
After:
Side note, with default lighting params in Gazebo, the bottle appears a lot darker than expected . In the screenshot above, I had to change the dir light diffuse and specular colors to [1.0 1.0 1.0] …
> Fix glTF metalness and roughness map orientation

- CMakeLists.txt
- Changelog.md
Preparation for 5.4.2 release.
Comparison to 5.4.1: https://github.com/gazebosim/gz-common/compare/gz-common5_5.4.1...gz-common5
> Prepare for 5.4.2 Release

- include/gz/common/EnumIface.hh
- src/EnumIface_TEST.cc
Fixes #505
Removes the use of the deprecated std::iterator template and replaces it with using the correct set of `using` statements.
I also added a `gzEnum` variadic template at clang's suggestion.  This should probably be preferred over the macro where relevant.
> Remove deprecated std::iterator inheritance

- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
When loading this [water bottle glb file](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WaterBottle), I manually saved the lightmap texture file (loaded by assimp) to examine what it looks like. It turns out the lightmap texture is just a copy of the [occlusion-metallic-roughness](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/WaterBottle/glTF/WaterBottle_occlusionRoughnessMetallic.png) texture, which is not correct.  There are issues reported upstream (see inline comments in code).
Currently if an occlusion-metallic-roughness texture exists, we extract the roughness texture map from the `g` channel and the metalness map is in the `b` channel of this texture.  I suspect that the right thing to do is to extract the `r` channel as a separate …
> Prevent loading lightmaps if mesh is a glb file that has an occlusion-metallic-roughness texture

- include/gz/common/EnumIface.hh
Fixes https://github.com/gazebosim/gz-common/issues/505, follow-up to #529.
The EnumIterator class inherits from std::iterator, which has been deprecated in c++17. There is a fix in gz-common6 (#529) but it breaks API, so it can't be merged to Garden. So just suppress the deprecation warning in Garden.
This should fix the gz-common5 brew builds:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_common-ci-gz-common5-homebrew-amd64&build=75)](https://build.osrfoundation.org/view/ign-garden/job/ignition_common-ci-gz-common5-homebrew-amd64/75/) https://build.osrfoundation.org/view/ign-garden/job/ignition_common-ci-gz-common5-homebrew-amd64/75/
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary …
> EnumIface: suppress deprecation warning

- .github/ci/packages.apt
- .github/workflows/ci.yml
- .github/workflows/macos.yml
- CMakeLists.txt
See https://github.com/gazebo-tooling/release-tools/issues/1027
> Bumps in ionic: use gz-cmake4, gz-utils3, gz-math8

- profiler/src/RemoteryProfilerImpl.cc
- src/SignalHandler.cc
- testing/include/gz/common/testing/CMakeTestPaths.hh
While testing https://github.com/gazebosim/gz-cmake/pull/392 I found that some visibility declarations were missing on Linux. Added them in this PR.
> Add missing visibility declarations

- profiler/src/RemoteryProfilerImpl.cc
- src/SignalHandler.cc
- testing/include/gz/common/testing/CMakeTestPaths.hh
Revert #548 until we can figure out how to fix Windows CI.
This reverts commit a52a7d2649317a0d8f47f82999e94846694105b9.
> Revert "Add missing visibility declarations (#548)"

- include/gz/common/Filesystem.hh
- src/Console.cc
- src/EnumIface_TEST.cc
- src/Filesystem.cc
Fixes a Segfault when building Ign common3 with pbuilder
If there is no write access to the log directory, the logger will call itself recusively in an infinite loop and segfault.
Note, this bug is also present in the latest version of ign common.
> Fix segfault in case of no write access to log dir

- src/Filesystem.cc
Found when debugging some of the Windows CI failures in `fuel_tools` here: https://github.com/gazebosim/gz-fuel-tools/pull/392
Instead of getting the output routed to gzerr, instead the macro gets expanded incorrectly yielding only:
```
7: [ RUN      ] CmdLine.ModelDownloadUnversioned
7: C:\J\workspace\gz_fuel_tools-pr-win\ws\gz-fuel-tools\src\gz_src_TEST.cc(195): error: Value of: this->stdErrBuffer.str().empty()
7:   Actual: false
7: Expected: true
7: [31m[Err] [C:\J\workspace\gz_fuel_tools-pr-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\gz_fuel_tools-pr-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\gz_fuel_tools-pr-win\ws\gz-common\src\Filesystem.cc:469] [m[31m[Err] [C:\J\workspace\gz_fuel_tools-pr-win\ws\gz-common\src\Filesystem.cc:469 …
```
> Fix error output when creating directories

- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
Supersedes #564 
Apologies for the noise! Hopefully third time is the charm? When working on #564 and #563 I realized that we do have a way to ship changes that depend on the assimp version, by using a define.
This allows us to have the fix in Harmonic (LTS) without being blocked by the fact that `gz-common4` is also shipped in Garden (that is short term support anyway).
If it's desirable I can open a PR targeting main that gets rid of all the `ifdef`s since they are only needed for compatibility with assimp 5.0.x that was last shipped in Ubuntu 20.04.
> Backwards compatible assimp texture name fix

- .github/workflows/ci.yml
- .github/workflows/triage.yml
- Changelog.md
- include/gz/common/Filesystem.hh
- profiler/src/ProfilerImpl.hh
- profiler/src/RemoteryProfilerImpl.hh
- src/Console.cc
- src/EnumIface_TEST.cc
- src/Filesystem.cc
Port `ign-common3 ` ➡️  `ign-common4`
Branch comparison: https://github.com/gazebosim/gz-common/compare/ign-common4...ign-common3
> Merge ign-common3 ➡️  ign-common4

- CMakeLists.txt
The default behavior of pkg-config seems to be an exact version match.
This was discovered when the RPM build process automatically added package dependencies based on the `*.pc` files generated by the project, one of which contained `gdal = 3.0`. This bug can be confirmed on any distro that has a gdal version other than 3.0, such as Ubuntu Jammy:
```
$ pkg-config --cflags gz-common5-geospatial
Package 'gz-common5-geospatial' requires 'gdal = 3.0' but version of gdal is 3.4.1
$ echo $?
1
```
It's interesting that the version comparison behaves differently in the first dependency level (which did not produce an error) than it does in subsequent levels. Perhaps there is a bug in `gz-cmake` as well.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to …
> Clarify GDAL version requirement

- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
- graphics/src/ColladaExporter_TEST.cc
- graphics/src/ColladaLoader.cc
- graphics/src/ColladaLoader_TEST.cc
- graphics/src/Image.cc
- graphics/src/OBJLoader_TEST.cc
- graphics/src/STLLoader_TEST.cc
- graphics/src/Skeleton.cc
- graphics/src/SkeletonAnimation_TEST.cc
- graphics/src/SkeletonNode.cc
Clean up remaining memory issues found with ASAN.  Unblocks some work on #569.
This fixes all asan issues except for one in `AudioDecoder`, which I'm going to skip for now.  I'm not convinced audio decoder is really doing the right thing (or the useful thing), and there are no downstream users for it.
> Multiple memory cleanup fixes

- CMakeLists.txt
- geospatial/src/CMakeLists.txt
Users building from source could get in a situation where dependencies of the `graphics` component weren't available, so that the component is not created.  In this case, the `geospatial` component still has a hard dependency on the `graphics` component, but it is still attempting to build.
This adds gating logic to prevent the `geospatial` component from building when the `graphics` component isn't build and adds a warning message for the user.
> Be louder when graphics is missing for geospatial

- CMakeLists.txt
- Changelog.md
Preparation for 5.5.0 release.
Comparison to 5.4.2: https://github.com/gazebosim/gz-common/compare/gz-common5_5.4.2...gz-common5
> Prepare for 5.5.0 release

- graphics/src/Image.cc
The issue is that if a pixel's color value in 8 bit format is close 1 (out of 255), when assigned to `math::Color`, `math::Color::Clamp` assumes it to be in the floating point range [0.0 - 1.0] instead of 8 bit unsigned range of [0 - 255]. The fix here is to convert colors to floating point at the source instead of relying on `Color::Clamp`.
Reference glTF file: [Damaged helmet](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/DamagedHelmet)
* Extract [DamagedHelmet.zip](https://github.com/gazebosim/gz-common/files/14466833/DamagedHelmet.zip) and run `gz sim test.sdf` from the same directory
> Fix noise issue that appears in certain image textures

- graphics/include/gz/common/MeshManager.hh
- graphics/src/ColladaLoader_TEST.cc
- graphics/src/MeshManager.cc
- graphics/src/MeshManager_TEST.cc
Add a new static function in MeshManager to merge all submeshes into one. The new function returns a new mesh with a single combined submesh
Note I also made the  `ConvexDecomposition` function that I added in https://github.com/gazebosim/gz-common/pull/585  static as it does not need to be a member function.
Added a test that merges two submehes and checked that all its vertices, normals, indices, and texcoords are correct.
Run the `UNIT_MeshManager_TEST`
> Add new function in MeshManager to merge all submeshes of a mesh into one

- graphics/src/MeshManager_TEST.cc
- io/src/CSVStreams.cc
- io/src/CSVStreams_TEST.cc
- profiler/src/CMakeLists.txt
Cleans up three sets of warnings:
* There were a few unnecessary `std::move` calls
* Adds a copy assignment operator to CSVIterator to fulfill rule-of-three
* Suppress some warnings in the vendored remotery code via CMake.
> Clean up Clang compiler warnings

- graphics/include/gz/common/MeshManager.hh
- graphics/src/ColladaLoader_TEST.cc
- graphics/src/MeshManager.cc
- graphics/src/MeshManager_TEST.cc
- graphics/src/VHACD/LICENSE
- graphics/src/VHACD/README.md
- graphics/src/VHACD/VHACD.h
Backport MeshManager's `ConvexDecomposition` (#585) and `MergeSubMeshes` (#588) functions that are used for doing convex decomposition.
> Backport MeshManager changes for doing convex decomposition

- BUILD.bazel
- Changelog.md
- av/BUILD.bazel
- events/BUILD.bazel
- geospatial/BUILD.bazel
- graphics/BUILD.bazel
- io/BUILD.bazel
- profiler/BUILD.bazel
- test/BUILD.bazel
- testing/BUILD.bazel
Port gz-common5 to main
Branch comparison: https://github.com/gazebosim/gz-common/compare/main...gz-common5
> port: 5 to main

- geospatial/include/gz/common/geospatial/Dem.hh
- geospatial/include/gz/common/geospatial/HeightmapData.hh
* Avoid users asking whether the height and elevation functions are the same
* Match common conventions like in GDAL to refer to things in "raster" coordinates with "pixels" indicating each point on a DEM
* Reference: https://gdal.org/tutorials/raster_api_tut.html
> Clarify units for the DEM classes

- CMakeLists.txt
- Changelog.md
Preparation for 5.6.0 release.
Comparison to 5.5.1: https://github.com/gazebosim/gz-common/compare/gz-common5_5.5.1...prep_5.6.0
> Prepare for 5.6.0 release

- av/src/AudioDecoder.cc
- av/src/Video.cc
- include/gz/common/EnumIface.hh
Fix deprecation warnings:
* Replace `avcodec_close` with `avcodec_free_context`
* Suppress deprecation of `std::iterator` since we can't change it without breaking ABI. I only did this for macOS, since that's the only platform that emits the warning.
> Fix deprecation warnings

- .github/workflows/ci.yml
- .github/workflows/package_xml.yml
- package.xml
Add `package.xml` based on dependencies found in `.github/ci/packages`. 
This is to test out using vendor packages to provide Gazebo packages to ROS users (see https://github.com/gazebo-tooling/release-tools/issues/1117).
> Add package.xml

- .github/workflows/macos.yml
- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
For glb meshes, our assimp loader generates a unique texture name for each embedded texture by prepending the 'scene' or 'root node' name of the glb mesh. However, the generated name may not always be unique. It's possible that different glb files have the same scene and root name. This PR adds the file base name of the mesh to the generated texture name string to make it more unique.
I think this change is similar to the intention in https://github.com/gazebosim/gz-common/pull/565 where it's also trying to make texture names unique.
> Generate a more unique texture name for glb embedded textures

- graphics/src/VHACD/VHACD.h
VHACD can be run [multi-threaded](https://github.com/gazebosim/gz-common/blob/27f7017c5c1b1fd2ba9c603e92b694f98417175d/graphics/src/MeshManager.cc#L1704), and TSAN picked up a data race issue:
```
SUMMARY: ThreadSanitizer: data race <path_to_gz-common>/graphics/src/VHACD/VHACD.h:5985:15 in VHACD::VoxelHull::VoxelHull(VHACD::VoxelHull const&, VHACD::SplitAxis, unsigned int)
```
Changing to an atomic type fixes the problem.
> Fix data race issue in VHACD found by TSAN

- graphics/include/gz/common/SubMesh.hh
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
Fixes #N/A
Previous version of `RecalculateNormals` member function has a O(n^2) complexity because inner loop where we are looking for normal elements. But we already know indexes of this elements. So we can get rid of inner loop.
And seems we should check `indices.size() < 3u || indices.size() % 3u != 0` due to if it will be 4, main loop will start and on second iteration it will start reading out of array.
Also seems condition in the begin should check amount of indexes/vector, but not normals, due to we are resizing it later.
Maybe this function also should have a check of `enum PrimitiveType` of data, seems attempt to call it for `POINTS` and `LINES` is not legit (for rest 4 types maybe it's ok, not sure)
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit …
> SubMesh::RecalculateNormals improvement

- .github/workflows/ci.yml
- CMakeLists.txt
- examples/CMakeLists.txt
- tutorials/profiler.md
Part of gazebosim/gz-cmake#350.
This adds a GitHub workflow using Noble and increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4.
Check CI results.
> Enable 24.04 CI, require cmake 3.22.1

- graphics/src/DelaunayTriangulation_TEST.cc
Adds a test for #623 
PR #623 ensures that Delaunay triangles have clockwise winding; this confirms that with a test using a cross product `(v2 - v1) x (v3 - v2)`. Since Z = 0 for all the vertices in this test, the cross product should have a negative Z component for clockwise winding (right-hand rule is positive for counter-clockwise, negative for clockwise).
> Test that Delaunay triangles wind clockwise

- CMakeLists.txt
- Migration.md
- graphics/src/CDT/README.md
- graphics/src/DelaunayTriangulation.cc
- graphics/src/DelaunayTriangulation_TEST.cc
- graphics/src/MeshManager.cc
Changes:
* Fixes triangle direction. The triangles returned from CDT are counter-clockwise, so convert them to clockwise in submesh. 
* Fixes style, lint issues
* Updated migration guide.
I have not moved CDT to its own `vendor` subdir yet. I just added a README.md with url and commit instead, similar to `VHACD`. 
> Fix triangulation with CDT and update migration guide

- graphics/src/AssimpLoader.cc
These debugging lines were added in https://github.com/gazebosim/gz-common/pull/597 when I fixed a small typo as part of a PR review.
> Remove debug logging introduced accidentally in PR review

- include/gz/common/Console.hh
- src/Console.cc
- src/Console_TEST.cc
With https://github.com/gazebosim/gz-utils/pull/142, it's no longer necessary to flush manually. This removes the need for `_fileInitialize` and fixes the behavior of `auto_default.log`.
> Remove flushes and fix tests

- CMakeLists.txt
- Changelog.md
Preparation for 6.0.0pre2 release.
Comparison to 6.0.0pre1: https://github.com/gazebosim/gz-common/compare/gz-common6_6.0.0-pre1...prep_6.0.0pre2
> Prepare for gz-common6.0.0~pre2 release

- graphics/src/AssimpLoader.cc
Fixes #633
Fixes `UNIT_AssimpLoader_TEST` with assimp 5.4.3. This should fix homebrew CI.
This PR tweaks the way we checks for texture coordinates from assimp. Empty texture coordinate slots are now allowed as of https://github.com/assimp/assimp/pull/5636. The new logic should be compatible with assimp 5.4.3 and prior versions
> Fix AssimpLoader collada texture coordinates

- graphics/src/AssimpLoader.cc
Fix loading gltf / glb mesh files with lightmaps. Needed by the Ionic demo world.
Currently the lightmap is ignored if there's a combined roughness + metalness texture. This PR fixes the problem by loading the lightmap (ambient occlusion data) from the roughness + metalness texture.
Tested with a few [gltf sample models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0) (water bottle, barramundi fish, damaged helmet)
Here are screenshots of the [BarramundiFish](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/BarramundiFish) before (left) and after (right) the change. I removed the albedo map to better visualize the effect of the lightmap:
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary …
> Fix loading lightmaps from gltf / glb meshes

- graphics/src/ColladaLoader_TEST.cc
- include/gz/common/Console.hh
- src/Console_TEST.cc
Fixes #632 
The severity level of `gzlog` was incorrectly set to `err`. Changing this to `trace` solves two problems:
1. The log message is now a lot less alarming 
2. When running `gz sim -v4`, this message is not shown on the console. It will only be logged to file. It does show up on the console if you run with `-v5`. 
The second point is technically a behavior change since in Harmonic, regardless of the verbosity level, `gzlog` would never show up on the console. However, duplicating that behavior with the new Console implementation proved to be very complicated. So, I propose we change the meaning of `gzlog` to be equivalent to `gztrace`.
---
**Note**
We'll have to make new prereleases of all downstream libraries for this fix to propagate. I vote we just wait for the stable release. …
> Fix severity level of gzlog

- tutorials/hw-encoding.md
The ffmpeg distributed via conda only has these encoders on win64:
```
(D:\programming\gz9-ws\conda) D:\programming\gz9-ws\gz-ws>ffmpeg -hide_banner -encoders | grep 264
V....D libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
V....D libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
V....D libopenh264          OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
V....D h264_mf              H264 via MediaFoundation (codec h264)
V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
```
I've added an explicit notice that Windows users with Intel GPUs won't have HW acceleration available out of the box.
If somebody knows about an easy way to provide a custom ffmpeg build with h264_qsv, it would be …
> docs/hw-encoding: Add a note about the conda-distributed ffmpeg on windows

- CMakeLists.txt
- Changelog.md
Preparation for 6.0.0 release.
Comparison to 6.0.0-pre2: https://github.com/gazebosim/gz-common/compare/gz-common6_6.0.0-pre2...gz-common6
Needed by <PR(s)>
> Prepare for 6.0.0 Release

- tutorials/install.md
Remove some references to GTS library, leftover from https://github.com/gazebosim/gz-common/pull/617 .
> Remove gts references from documentation

- graphics/src/AssimpLoader.cc
Backport #630 
**Note to maintainers**: Remember to **rebase and merge** with commit
> Backport glb lightmap fix

- CMakeLists.txt
- Changelog.md
- examples/CMakeLists.txt
- package.xml
- tutorials/profiler.md
Bump main to gz-common 7.0.0~pre1
> Bump main to gz-common 7.0.0~pre1

- examples/console.cc
This patch adds newlines to the logging messages and tweak some of the comments.
> Adds EoL to console example

- graphics/src/SVGLoader.cc
Transitive header wasn't being accounted for and this got broken by https://github.com/gazebosim/gz-math/pull/589
> Include math::Angle since it is used here

- CMakeLists.txt
- Changelog.md
- package.xml
Preparation for 5.7.0 release.
Comparison to 5.6.0: https://github.com/gazebosim/gz-common/compare/gz-common5_5.6.0...gz-common5
> Prepare for 5.7.0 Release

- include/gz/common/Util.hh
- src/Util.cc
As part of the Ionic tick-tock process, we're updating this function in favor of the version with three arguments. We also make the three version function works with two arguments only.
> Deprecate env() with two parameters

- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
A missing header and a couple of tweaks to make the MSVC compiler happy.
Complaining: https://build.osrfoundation.org/view/conda/job/gz_common-5-cwin/1/msbuild/
Fixed: https://build.osrfoundation.org/job/_test_gz_common-pr-cwin/8/
> Remove Conda Windows warnings

- graphics/src/AssimpLoader.cc
Fixes there isn't a bug number
An assimp mesh could contain either
- the same number of vertices and normals
- only vertices
Existing code crashes when a mesh contains no normals
> Check normal presence before trying to read asMesh normals

- CMakeLists.txt
- Changelog.md
- package.xml
Preparation for 6.0.1 release.
Comparison to 6.0.0: https://github.com/gazebosim/gz-common/compare/gz-common6_6.0.0...gz-common6
> Prepare for 6.0.1 Release

- events/include/gz/common/Event.hh
No bug number.
An issue revealed in https://github.com/microsoft/STL/pull/5105, that can be fixed by including `<chrono>`.
```log
include\gz\common5\gz/common/Event.hh(89): error C2039: 'system_clock': is not a member of 'std::chrono'
```
> Add include <chrono> for system_clock

- test/performance/logging.cc
- testing/include/gz/common/testing/detail/AutoLogFixture.hh
Hi,
This fix a couple of missing includes:
```cpp
In file included from /build/source/testing/include/gz/common/testing/AutoLogFixture.hh:58,
from /build/source/src/MaterialDensity_TEST.cc:20:
/build/source/testing/include/gz/common/testing/detail/AutoLogFixture.hh: In member function 'virtual void gz::common::testing::AutoLogFixture::SetUp()':
/build/source/testing/include/gz/common/testing/detail/AutoLogFixture.hh:79:8: error: 'replace' is not a member of 'std'
79 |   std::replace(this->dataPtr->logFilename.begin(),
|        ^~~~~~~
```
and
```cpp
/build/source/test/performance/logging.cc: In function 'void {anonymous}::PrintStats(const std::string&, const std::map<long unsigned int, std::vector<long unsigned int> >&, uint64_t)':
/build/source/test/performance/logging.cc:79:16: error: …
```
> add missing includes

- CMakeLists.txt
- Changelog.md
Preparation for 3.17.1 release.
Comparison to 3.17.0: https://github.com/gazebosim/gz-common/compare/ignition-common3_3.17.0...ign-common3
Part of https://github.com/gazebo-tooling/release-tools/issues/1252
> Prepare for 3.17.1 Release

- graphics/src/AssimpLoader_TEST.cc
Small fix, Windows warnings related to C4305 in a couple of tests.
C++ literals default to `double`, and Windows build it's complaining because `EXPECT_FLOAT_EQ` test macros are expecting the use of a `float` type. Changing the literals to use `f`, so they should be using float now.
> Fix C4305 double truncated to float warnings

- graphics/include/gz/common/SubMesh.hh
- graphics/src/SubMesh.cc
- graphics/src/SubMesh_TEST.cc
Check for valid indices in submesh before doing operations that make use of them, e.g. `RecalculateNormals` or `Volume` functions. Each index should point to an element in the vertices array. So the check makes sure that we don't have an invalid index that tries to access an element that is out of range of the vertices array. 
> Add check for valid indices in submesh

- .github/workflows/ci.yml
- graphics/src/AssimpLoader.cc
- graphics/src/AssimpLoader_TEST.cc
- include/gz/common/Console.hh
Part of Part of https://github.com/gazebo-tooling/release-tools/issues/1222
Enable linters on Noble. There are doxygen complaints, so just enable cppcheck and cpplint for now.
> ci: run cppcheck, cpplint on noble

- graphics/src/MeshManager.cc
Same idea as in https://github.com/gazebosim/gz-common/pull/667. This PR adds sanity check for valid indices before doing convex decomposition on the submesh.
> Check valid indices before doing convex decomposition

- profiler/BUILD.bazel
- profiler/include/gz/common/Profiler.hh
- profiler/include/gz/common/ProfilerImpl.hh
- profiler/src/CMakeLists.txt
- profiler/src/Profiler.cc
- profiler/src/Profiler_Custom_TEST.cc
- profiler/src/Profiler_Disabled_TEST.cc
- profiler/src/Profiler_Error_TEST.cc
- profiler/src/RemoteryProfilerImpl.hh
Backports https://github.com/gazebosim/gz-common/pull/682 to gz-common5.
Repeating the change description here for posterity:
Allow custom profiler implementations to be used with gz-common profiler.
The following changes are made to support this feature:
- A new `SetImplementation` method is added in the singleton Profiler class to set a profiler implementation.
- This method returns false if an implementation is already in use. This is to avoid complexity from profiler implementations having to be robust against being enabled in the middle of existing scoped profile calls.
- As a side-effect, `SetImplementation` can only be called once in the process lifetime with a valid profiler implementation.
- The ProfilerImpl.hh header is moved from profiler/src/ to profiler/include/gz/common/ to …
> Backport support for custom profiler implementation from gz-common6

- MODULE.bazel
Fixes bazel build with `--dynamic_mode=off` by pulling in a newer version of assimp (bumped in https://github.com/bazelbuild/bazel-central-registry/pull/4724, please read the PR description there for details on the error and the fix). 
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> Bump assimp version to fix build with --dynamic_mode off

- Migration.md
- include/gz/common/MovingWindowFilter.hh
- src/MovingWindowFilter_TEST.cc
Deprecate unused feature now present in gz-math
The `gz::common::MovingWindowFilter` class was copied to gz-math 4 in [bitbucket pull request 239](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/239/page/1). The gz-common version is [no longer used in the gazebosim org](https://github.com/search?q=org%3Agazebosim%20common%2FMovingWindowFilter.hh&type=code), so deprecate it.
Check that CI has no deprecation warnings.
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> Deprecate MovingWindowFilter, use gz-math instead

- graphics/include/gz/common/Image.hh
- graphics/src/AssimpLoader.cc
- graphics/src/Image.cc
- graphics/src/Image_TEST.cc
Related to https://github.com/gazebosim/jetty_demo/issues/3
Adds a new `Image::ChannelData` function to help extract a single channel (r, g, b, or a) from an RGB[A] image.
Thanks for profiling data from @azeey, it was found when loading the Jetty demo world a big chunk of time is spend on splitting the metallic and roughness maps of glb meshes. The main cause of slow down is found to be the [Image::Pixel](https://github.com/gazebosim/gz-common/blob/1edb8408361cc1662e545a328dfaf354db4c20fb/graphics/src/Image.cc#L425) function as the AssimpLoader iterates through every pixel in the image. With the new `Image::ChannelData` function, the AssimpLoader now has a faster and more efficient way of retrieving different channels of the input image. 
Note that the perf issue with `Image::Pixel` …
> Add function for extracting single channel data from an RGB[A] image

- MODULE.bazel
Bump spdlog dep in Bazel build to 1.15.3 ([latest](https://registry.bazel.build/modules/spdlog)) to fix a compilation issue on MacOS Sequoia. The issue stemmed from pulling in an older unsupported version of `fmt` [transitively](https://github.com/bazelbuild/bazel-central-registry/blob/301ac69537d17e89563609b59562d58a7fb3d982/modules/spdlog/1.12.0/MODULE.bazel#L7):
```
external/fmt~/src/os.cc:300:12: error: out-of-line definition of 'pipe' does not match any declaration in 'fmt::file'
300 | void file::pipe(file& read_end, file& write_end) {
|            ^~~~
external/fmt~/src/os.cc:373:6: error: use of undeclared identifier 'file_buffer'
373 | void file_buffer::grow(size_t) {
|      ^
external/fmt~/src/os.cc:377:1: error: use of undeclared identifier 'file_buffer'
377 | …
```
> [bazel] Bump spdlog version
